sudo : false

language: python

python:
  - 3.6

before_install:
 - pip install --upgrade pip

install:
 - pip install -qq flake8
# - pip install .

script:
  - flake8 --version
  - flake8 --ignore E501 *.py

notifications:
  email: false
